# Generated by Django 3.2.16 on 2022-11-13 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True,
                                          verbose_name='Название')),
                ('color',
                 models.CharField(max_length=7, null=True, unique=True,
                                  verbose_name='Цвет в HEX')),
                ('slug',
                 models.SlugField(max_length=200, null=True, unique=True,
                                  validators=[
                                      django.core.validators.RegexValidator(
                                          regex='[-a-zA-Z0-9_]+$')],
                                  verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'db_table': 'tags',
            },
        ),
    ]
