# Generated by Django 3.2.16 on 2022-11-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('name',
                 models.CharField(max_length=200, verbose_name='Название')),
                ('measurement_unit', models.CharField(max_length=200,
                                                      verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'db_table': 'ingredients',
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('id',), 'verbose_name': 'Тег',
                     'verbose_name_plural': 'Теги'},
        ),
    ]
