# Generated by Django 3.2.16 on 2022-11-19 11:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0006_auto_20221119_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipetags',
            options={'verbose_name': 'Тег в рецептах',
                     'verbose_name_plural': 'Теги в рецептах'},
        ),
    ]
