# Generated by Django 3.2.16 on 2022-11-25 20:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0008_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredientamount',
            options={'ordering': ('-id',), 'verbose_name': 'Ингредиент',
                     'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterField(
            model_name='favoriterecipes',
            name='recipe',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='favorites', to='recipes.recipe',
                verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='favoriterecipes',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='favorites', to=settings.AUTH_USER_MODEL,
                verbose_name='Подписчик'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipeingredientamount',
            name='amount',
            field=models.FloatField(blank=True, validators=[
                django.core.validators.MinValueValidator(1)],
                                    verbose_name='Количество'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(
                fields=('name', 'measurement_unit'),
                name='Unique name measurement_unit required'),
        ),
    ]
