# Generated by Django 3.2.16 on 2022-11-25 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0009_auto_20221125_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0.1)],
                verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipeingredientamount',
            name='amount',
            field=models.FloatField(blank=True, validators=[
                django.core.validators.MinValueValidator(0.1)],
                                    verbose_name='Количество'),
        ),
    ]
